name: CI
on:
  pull_request:
    branches: [master]
  push:
    branches:
      - master
      - ci

env:
  CARGO_TERM_COLOR: always
  ROCM_VERSION: "6.1.3"

jobs:
  build_win_5:
    name: Build (Windows)
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Install AMD HIP SDK 5.7
        run: |
          C:\msys64\usr\bin\wget.exe https://download.amd.com/developer/eula/rocm-hub/AMD-Software-PRO-Edition-23.Q4-Win10-Win11-For-HIP.exe -O "amdgpu-install.exe"
          .\amdgpu-install.exe -Install -View:1
          Start-Sleep -Seconds 60
          $setupId = (Get-Process ATISetup).id
          Wait-Process -Id $setupId
      - uses: Swatinem/rust-cache@v2
      - name: Build for ROCm 5.x
        run: |
          $ROCm_PATH = "C:\Program Files\AMD\ROCm"
          $Env:HIP_PATH = "$ROCm_PATH\$(Get-ChildItem -Path $ROCm_PATH -Name)"
          $Env:PATH = "$Env:HIP_PATH\bin;$Env:PATH"
          $Env:HIP_PATH = "$Env:HIP_PATH\"
          cargo xtask -r --rocm5

  build_win_6:
    name: Build (Windows)
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Install AMD HIP SDK 6.1
        run: |
          C:\msys64\usr\bin\wget.exe https://download.amd.com/developer/eula/rocm-hub/AMD-Software-PRO-Edition-24.Q3-Win10-Win11-For-HIP.exe -O "amdgpu-install.exe"
          .\amdgpu-install.exe -Install -View:1
          Start-Sleep -Seconds 60
          $setupId = (Get-Process ATISetup).id
          Wait-Process -Id $setupId
      - uses: Swatinem/rust-cache@v2
      - name: Build for ROCm 6.x
        run: |
          $ROCm_PATH = "C:\Program Files\AMD\ROCm"
          $Env:HIP_PATH = "$ROCm_PATH\$(Get-ChildItem -Path $ROCm_PATH -Name)"
          $Env:PATH = "$Env:HIP_PATH\bin;$Env:PATH"
          $Env:HIP_PATH = "$Env:HIP_PATH\"
          cargo xtask -r
