name: Rust
on:
  push:
    branches: [master]
  push:
    branches:
      - master
      - ci

env:
  CARGO_TERM_COLOR: always
  ROCM_VERSION: "6.1.3"

jobs:
  build_win_5:
    name: Build and publish (Windows)
    runs-on: windows-2019
    needs: release
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Install AMD HIP SDK 5.7
        run: |
          C:\msys64\usr\bin\wget.exe https://download.amd.com/developer/eula/rocm-hub/AMD-Software-PRO-Edition-23.Q4-Win10-Win11-For-HIP.exe -O "amdgpu-install.exe"
          .\amdgpu-install.exe -Install -View:1
          Start-Sleep -Seconds 60
          $setupId = (Get-Process ATISetup).id
          Wait-Process -Id $setupId
      - uses: Swatinem/rust-cache@v2
      - name: Build for ROCm 5.x
        run: |
          $ROCm_PATH = "C:\Program Files\AMD\ROCm"
          $Env:HIP_PATH = "$ROCm_PATH\$(Get-ChildItem -Path $ROCm_PATH -Name)"
          $Env:PATH = "$Env:HIP_PATH\bin;$Env:PATH"
          $Env:HIP_PATH = "$Env:HIP_PATH\"
          cargo xtask zip -r --rocm5
          Expand-Archive -Path target/release/zluda.zip -DestinationPath target/release
      # https://stackoverflow.com/a/74033027
      - name: Set revision hash
        run: echo "SHORT_SHA=$("${{ github.sha }}".SubString(0, 7))" >> $env:GITHUB_ENV
      - name: Upload (artifact)
        uses: actions/upload-artifact@v4
        with:
          name: zluda-windows-rocm5-${{ env.SHORT_SHA }}
          path: target/release/zluda
      - name: Upload (release)
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.release.outputs.upload_url }}
          asset_path: target/release/zluda.zip
          asset_name: ZLUDA-windows-rocm5-amd64.zip
          asset_content_type: application/zip

  build_win_6:
    name: Build and publish (Windows)
    runs-on: windows-2019
    needs: release
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Install AMD HIP SDK 6.1
        run: |
          C:\msys64\usr\bin\wget.exe https://download.amd.com/developer/eula/rocm-hub/AMD-Software-PRO-Edition-24.Q3-Win10-Win11-For-HIP.exe -O "amdgpu-install.exe"
          .\amdgpu-install.exe -Install -View:1
          Start-Sleep -Seconds 60
          $setupId = (Get-Process ATISetup).id
          Wait-Process -Id $setupId
      - uses: Swatinem/rust-cache@v2
      - name: Build for ROCm 6.x
        run: |
          $ROCm_PATH = "C:\Program Files\AMD\ROCm"
          $Env:HIP_PATH = "$ROCm_PATH\$(Get-ChildItem -Path $ROCm_PATH -Name)"
          $Env:PATH = "$Env:HIP_PATH\bin;$Env:PATH"
          $Env:HIP_PATH = "$Env:HIP_PATH\"
          cargo xtask zip -r
          Expand-Archive -Path target/release/zluda.zip -DestinationPath target/release
      # https://stackoverflow.com/a/74033027
      - name: Set revision hash
        run: echo "SHORT_SHA=$("${{ github.sha }}".SubString(0, 7))" >> $env:GITHUB_ENV
      - name: Upload (artifact)
        uses: actions/upload-artifact@v4
        with:
          name: zluda-windows-rocm6-${{ env.SHORT_SHA }}
          path: target/release/zluda
      - name: Upload (release)
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.release.outputs.upload_url }}
          asset_path: target/release/zluda.zip
          asset_name: ZLUDA-windows-rocm6-amd64.zip
          asset_content_type: application/zip
